name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  ENV_MODE: 'production'
  MAIL_USER: ${{ secrets.MAIL_USER }}
  MAIL_PASS: ${{ secrets.MAIL_PASS }}

jobs:
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 128.65.195.180
          username: oo7ed_sarah
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./